### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by luisherranz** [percolatestudio/atmosphere#368] opened 2015-04-14 14:36 UTC
It looks like atmosphere is not rendering all the titles correctly.
Check Examples or Use:
https://atmospherejs.com/meteorflux/reactive-dependency

In Github all of them are render correctly:
https://github.com/meteorflux/reactive-dependency

**Comment by tmeasday** [comment] 2015-04-21 03:51
I'd guess this is a dupe of #345. Thanks @LuisHerranz

**Closed as completed** 2015-04-21 03:51 UTC
Labels: bug
