### ISSUE TITLE
Is app installs counter broken?

### ISSUE THREAD

**Issue by barbatus** [percolatestudio/atmosphere#420] opened 2016-01-01 05:48 UTC
I noticed that counters for some new packages are zero for a week or so already (e.g. https://atmospherejs.com/kadira/graphql)

**Comment by dburles** [comment] 2016-01-05 07:01
+1

**Comment by selaias** [comment] 2016-01-08 13:13
+1

**Comment by dufia** [comment] 2016-01-16 23:55
+1

**Comment by tmeasday** [comment] 2016-01-19 00:03
Hi all, yes it is broken, fix coming very soon, thanks for the reports.

**Comment by barbatus** [comment] 2016-02-03 07:44
@tmeasday how does it work? It seems failing to count properly again...

**Comment by tmeasday** [comment] 2016-02-03 22:33
Hi @barbatus - I think the problem is fixed now. Are you still seeing problems? Can you post a specific example?

**Closed as completed by tmeasday** 2016-02-03 22:33 UTC

**Comment by barbatus** [comment] 2016-02-04 09:18
@tmeasday I am sure this pkg https://atmospherejs.com/barbatus/ionic2-meteor was installed multiple times while the counter shows zero.

**Comment by dufia** [comment] 2016-02-04 10:13
I think Top Searches section is broken too but I am not 100% sure :)
