### ISSUE TITLE
packages still searchable even after meteor admin set-unmigrated

### ISSUE THREAD

**Issue by archived-aft-bogus-german-visa-rejectio** [percolatestudio/atmosphere#333] opened 2015-01-18 15:08 UTC
I tried hiding two packages of mine (`arch:fermions` and `arch:template-bulter`)  using `meteor admin set-unmigrated` and I got `Setting arch:packageName@x.x.x as successfully migrated ... done.` but I can still see them on atmosphere the next day.

**Comment by tmeasday** [comment] 2015-01-20 05:23
Hey @0a- we're currently having some problems syncing. Should be fixed pretty soon. https://github.com/percolatestudio/atmosphere/issues/332

**Comment by tmeasday** [comment] 2015-01-20 06:37
The problem is fixed @0a- but I think maybe you didn't do it right. It still shows up in `meteor show` for me too.

**Comment by ghost** [comment] 2015-01-20 14:42
Ooh thanks.  `template-bulter` (a misspell of `template-butler`) is not showing up anymore. I will try doing set-unmigrated for `fermions` again when I get back on my mac.

**Comment by ghost** [comment] 2015-01-22 15:02
Yup. It worked perfectly. Seems like `fermions` showed up only because I did a `unmigrated --success` for it (now then I recalled).

**Closed as completed by ghost** 2015-01-22 15:02 UTC
