### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by mquandalle** [percolatestudio/atmosphere#166] opened 2014-06-03 22:51 UTC
In harmony [smart.json](https://github.com/mquandalle/meteor-harmony/blob/master/smart.json), we define two (co-)authors, but there is only one displayed [on atmosphere](https://atmospherejs.com/package/harmony), so that's a bug :-)

Note that this field has been modified after the first release.

**Comment by tmeasday** [comment] 2014-06-03 22:54
You are correct in guessing the problem is that the field changed since initial release. Not a great system right now.

**Comment by domyen** [comment] 2014-09-12 01:13
This appears to be resolved. Closing.

**Closed as completed by domyen** 2014-09-12 01:13 UTC
