### ISSUE TITLE
Something's up with livescript

### ISSUE THREAD

**Issue by ndarilek** [percolatestudio/atmosphere#119] opened 2014-04-09 17:15 UTC
I use the livescript package in an app, and it fails to download from the new Atmosphere. More specifically:
1. The current livescript package appears to be dead. Meteorite attempts to download it but the repository no longer exists.
2. If I use livescript-latest, I'm prompted to confirm an SSH key fingerprint for Github despite the fact that the repository is checked out over HTTPS. I suspect most won't encounter this problem, only I'm developing in a Docker container so there is no SSH setup. I've duplicated this on multiple machines, so it should be pretty easy to move known_hosts aside for a bit. Checking out the repository via git clone works and, likewise, when the repo is checked out then others in the set of dependencies work well.

This could be a Meteorite issue, but since mrt hits Atmosphere, I'm wondering if perhaps it's being served bad data for this package.

Thanks!

**Comment by tmeasday** [comment] 2014-04-10 02:53
Are you sure you don't have any packages that are checking out over `ssh://` (check your `smart.lock` to be sure)?

I can't see why it would call out to ssh to access a `https://` URL. If anything this sounds like a github issue?

**Comment by ndarilek** [comment] 2014-04-10 04:16
Absolutely sure, I've grepped for ssh and have wiped my smart.lock 
multiple times. I can check out the https URL fine without this issue. 
It doesn't make any sense to me but I can reliably reproduce with the 
steps included.

**Comment by tmeasday** [comment] 2014-04-10 04:19
I don't really know the specifics of the git protocol and specifically how github does it.

Can you git clone that URL on one of these machines?

**Comment by ndarilek** [comment] 2014-04-10 04:39
Yes.

Do the steps of:
1. Move ~/.ssh/known_hosts out of the way.
2. Run a Meteor app with the "livescript-latest" package in its 
   dependency list.

not duplicate the issue for you? Again, it happens on multiple machines 
for me.

**Comment by tmeasday** [comment] 2014-04-10 05:47
Ahh! The issue is that the package includes a submodule with a `ssh` git URL. Get the author to change that ...

**Comment by tmeasday** [comment] 2014-04-16 02:33
I'm going to close this. If you want to track it further, can we move the discussion to https://github.com/oortcloud/meteorite

**Closed as completed by tmeasday** 2014-04-16 02:33 UTC
