### ISSUE TITLE
History position is broken ?

### ISSUE THREAD

**Issue by cristiandley** [percolatestudio/atmosphere#262] opened 2014-10-07 13:10 UTC
# History position is broken or is a new desing ?

![CAPTURE](https://cloud.githubusercontent.com/assets/1873659/4542577/198d84be-4e23-11e4-8a18-3b458a87c4e3.png)

**Comment by domyen** [comment] 2014-10-12 00:33
thanks for the heads up. I believe this is a dupe of #259.

**Closed as completed by domyen** 2014-10-12 00:33 UTC
