### ISSUE TITLE
Feature request: Favourite packages

### ISSUE THREAD

**Issue by html5cat** [percolatestudio/atmosphere#223] opened 2014-09-23 22:05 UTC
It would be awesome to have ability to favourite/star package to later return to them or see your (or others') list of favourites.
Favouriting on Atmosphere could also start the repo on github, thus encouraging great packages and having a bit more visibility.
Thanks!

**Comment by domyen** [comment] 2014-09-23 22:42
Soon :)  Dupe of https://github.com/percolatestudio/atmosphere-beta/issues/57.

**Closed as completed by domyen** 2014-09-23 22:42 UTC
