### ISSUE TITLE
[minor] Reactively update the README

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#286] opened 2014-10-29 05:03 UTC
I've noticed that as soon as I `meteor publish` a package, its Atmosphere page refreshes with the new version. Neat!

However, if the new package added a git URL, the README isn't updated.

**Comment by tmeasday** [comment] 2014-10-30 05:39
Mmm. That'd be a neat trick :)

**Comment by msavin** [comment] 2015-02-24 00:10
I'm experiencing the issue still - very odd that this isn't supported out of the box. Could we have an ETA on when this will be fixed? 

Note: I am updating the readme.md with-in the package, and also on GitHub.

**Comment by tmeasday** [comment] 2015-02-24 03:20
I'm actually confused about what this original ticket was about.

@msavin - what exact issue are you having?

**Comment by msavin** [comment] 2015-02-24 03:28
@tmeasday Thanks for the quick response!

Basically - when you upload a package, Atmosphere will pull its readme.md file and set it as the content for the package. But whenever you update that file on Git or with-in the package, it doesn't update. It's caused me a bit of frustration as one of my packages is trending but I could not update its readme content.

Compare: 
http://github.com/msavin/Mongol
https://atmospherejs.com/msavin/mongol

I've tried to update the readme.md on the package itself and the repo, as well as renaming it in the package.js file an attempt to reset.

**Comment by tmeasday** [comment] 2015-02-24 03:56
Hi @msavin - great package btw!

Hmm, it seems on the surface that something is wrong here. @zol can you take a look?

**Comment by msavin** [comment] 2015-02-24 04:18
Thanks. Also worth a note; the download numbers only seem to update every day or so.

**Comment by zol** [comment] 2015-02-24 20:18
@msavin I've pushed a fix to your readme refresh issue. It was caused by a small regression from our recent readme overhaul. You should now find that after changing your readme on github and visiting your package page (don't forget to reload) the readme will update.

I've opened #349 to track the install count issue.

@dandv could you please check to see if your issue is now fixed (don't forget to refresh the package page, its required to initiate a GET req for the github readme).

Thanks everyone.

**Comment by msavin** [comment] 2015-02-24 22:19
So nice! Thank you.

**Comment by tmeasday** [comment] 2015-04-21 03:59
@dandv I'm going to close this -- ping me if it indeed is not fixed.

**Closed as completed by tmeasday** 2015-04-21 03:59 UTC
Labels: enhancement
