### ISSUE TITLE
Organization logos/icons/avatars?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#352] opened 2015-03-03 08:27 UTC
https://atmospherejs.com/dandv shows a few of my collaborators being organizations for the 3rd party libraries I helped integrate. Is there a way to add logos to the profiles of those organizations?

**Comment by cvrebert** [comment] 2015-03-22 06:51
:+1:

**Comment by splendido** [comment] 2015-03-22 07:02
:+1:

**Comment by cvrebert** [comment] 2015-03-22 07:29
Semi-duplicate of #319.

**Comment by tmeasday** [comment] 2015-04-21 03:46
I'm going to close this as it's covered by #319

**Closed as completed by tmeasday** 2015-04-21 03:46 UTC
Labels: enhancement
