### ISSUE TITLE
DDP access and Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by gadicc** [percolatestudio/atmosphere#299] opened 2014-11-13 17:01 UTC
Hey :)

Is it ok for (responsible) developers to open DDP connections to `https://atmospherejs.com/`?  When I try, I get:

```
XMLHttpRequest cannot load https://atmospherejs.com/sockjs/info?cb=968c1jx866.
The 'Access-Control-Allow-Origin' header contains multiple values
'http://localhost:3000, *', but only one is allowed. Origin
'http://localhost:3000' is therefore not allowed access.
```

Indeed, the headers come like this:

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:3000
Access-Control-Allow-Origin:*
...
Vary:Origin
```

So, looks like in theory you allow it but there's an extra header in there.  Maybe the app code is adding the first that was maybe originally intended for development, and the second is coming from the proxy config?

**Comment by zol** [comment] 2014-11-19 23:33
Hey @gadicc. The duplicate Access-Control-Allow-Origin header has been fixed in our proxy config. 

Regarding DDP access, you can now theoretically connect to atmosphere's DDP connection directly. What are you hoping to do? In the past we've suffered outages when people have connected and performed naive operations (such as subscribing to way too much data). 

Unfortunately, it's trivially easy to hose a Meteor app over DDP. If it happens again we will likely disable direct access completely.

**Closed as completed by zol** 2014-11-19 23:33 UTC

**Comment by gadicc** [comment] 2014-11-20 04:58
Hey, awesome.. thanks, @zol!

Yeah, I totally understand that of course.  If that happens again maybe we can work out a better solution.

We started a plugins page at http://famous-views.meteor.com/plugins.  Just wanted to show Atmosphere stars and downloads next to each one.  So, would be the same subs as `?q=fview-` on Atmosphere, and of course, unsub when leaving that page/route.

I guess if we start having many simultaneous users we could open the DDP connection just once from the server instead.  But at this stage the occasional user on that page will definitely amount to less resources.

**Comment by zol** [comment] 2014-11-22 22:40
Cool, that seems ok.

**Comment by gadicc** [comment] 2014-11-24 10:09
Haha, so, I promised to be careful and then @splendido sent this to me via IM:

> Hi Gadi!
> ....just wanted to let you know your DDP connection to Atmosphere threw everything down! Atmosphere is not fetching package data at the moment

my heart skipped a beat until the next line showed up,
"I'm kidding, off course!".

#hadtoshare :)

**Comment by splendido** [comment] 2014-11-24 10:13
it was just to add a bit of fun to the morning ;-)
Despite this, the problem is there: atmosphere is loading correctly with no issues inside the browser console, but local collections are not being populated... hence no contents!

Have a nice day! :-)

**Comment by gadicc** [comment] 2014-11-24 10:16
It's ok, I lol'd, just got a big fright initially :>

Oh ok if it's a real problem then open an issue on our repo.  In general we only establish the DDP connection to atmosphere if the user browses to the plugins page, so it takes a bit longer.  For me the counts show up after about 2s from loading the page... maybe your internet connection is slow :>

**Comment by splendido** [comment] 2014-11-24 10:21
mmm, weird, I was sure it could have been the same for all.
I have both sites open since a while, but nothing is showing up:

![atmosphere_no_package_data](https://cloud.githubusercontent.com/assets/6148980/5163432/e169454a-73cb-11e4-8ed0-5e4b0f8e7623.png)
![fview_no_package_data](https://cloud.githubusercontent.com/assets/6148980/5163437/eed34456-73cb-11e4-94c7-7ec96e31d5b7.png)

and my connection seems ok.

If it's a problem only on my side, please don't consider it. There might be something wrong with some router around here in Italy ;-)

**Comment by splendido** [comment] 2014-11-24 10:26
mmm, it turns out the problem is with my chrome: Version 40.0.2214.10 beta (64-bit) on Ubuntu 14.04
Bot Firefox and Chrome on my mobile are fine!
Might be still relevant, but I guess I'd need to investigate more...

Sorry for the rumor guys!

**Comment by gadicc** [comment] 2014-11-24 11:15
Atmosphere not working on a particular Chrome version is something we should know about.  Are DDP connections to any other sites affected?  Sure, keep investigating and keep us posted.

**Comment by splendido** [comment] 2014-11-24 11:49
Other websites works normally, Crater.io for example...

But now also Chrome worked!
...even with huge waiting times...
What I can see from the websocket traffic on the network log is that initial subscriptions to 'packages/*' like:

 ["{\"msg\":\"sub\",\"id\":\"YEh8kTc3kJLXuhxTM\",\"name\":\"packages/trending\",\"params\":[]}"]

get replies in 5 to 10 minutes...

a["{\"msg\":\"added\",\"collection\":\"packages\",\"id\":\"vGubXFE2zGaWzYMZP\",\"fields\":{\"authorName\":\"mizzao\",\" ... ...]

from 12.23.58PM to 12.32.16PM in a first attempt and from 12.35.47PM to 12.40.56PM in a second one.

Still on Firefox is more or less instantaneous,  so I guess it's not because meteor.com is having big traffic...

Thoughts?

**Comment by gadicc** [comment] 2014-11-24 14:24
Uh, no :>  How many tabs do you have open?  If you restart Chrome, any difference?  With extensions disabled?

**Comment by splendido** [comment] 2014-11-24 14:51
Tried to restart, and no change, at least this morning.
...very few tabs opened, an just plain html.

The thing is now is working fine!!!! :-(

**Comment by zol** [comment] 2014-11-24 17:41
About 7 hours ago our servers were experiencing some problems due to a change we made in score calculations. This may explain the flakiness you were experiencing.

**Comment by splendido** [comment] 2014-11-24 17:44
Ok, that's good to know.
...and I guess it also has something to do with #132 right?

Tnx for letting us know!

**Comment by gadicc** [comment] 2014-11-27 04:38
@zol, I think I'd prefer now to do the DDP from the server.  Are you ok with a "single" set of the same queries (it's actually a lot less than `?q=fview` on atmosphere, since we don't subscribe to the daily scores, etc) being left on 24/7?

otherwise i can just cache the results on the server, and have the server connect and update on debounced visits to the page (you can let me know what threshold you're comfortable with).

**Comment by zol** [comment] 2014-12-08 17:03
Hey @gadicc sorry for the late reply this somehow slipped through the cracks. Yeah it's fine if you leave the server connected 24/7 for the time being.

**Comment by gadicc** [comment] 2014-12-12 13:03
No problem at all, it is a closed issue after all :>  Thanks for confirming!  All done our side :)  Even have the DDP disabled by default when running in development instances :>
