### ISSUE TITLE
List new packages

### ISSUE THREAD

**Issue by arunoda** [percolatestudio/atmosphere#44] opened 2014-02-20 04:13 UTC
We need a list of newly added and updated packages as well.

**Comment by ai10** [comment] 2014-02-20 14:24
yes; freshmeat may be more interesting than trending.

**Comment by Lauricio** [comment] 2014-02-21 12:51
definitely

**Comment by queso** [comment] 2014-02-21 21:29
:+1:  I assume there is a freshness built into the package ranking?  I am sure there comes a point where a lack of updates might indicate dead projects...

**Comment by zol** [comment] 2014-02-21 21:34
Yes there is. We also factor in install count as a lack of updates but a high number of installs may signal a mature, well loved package.

**Comment by tmeasday** [comment] 2014-02-27 23:47
Going to close this as a dupe of #28

**Closed as completed by tmeasday** 2014-02-27 23:47 UTC
Labels: duplicate
